### ISSUE TITLE
Spinning Circle on EPG

### ISSUE THREAD

**Issue by 49studebaker** [google/sagetv#116] opened 2016-03-27 02:08 UTC
If I scroll through the EPG, I get the spinning circle. I think a SageTV developer, told me that SageTV is retrieving data from the internet. Could you fork this retrieval process so that it does not slow down the interface?

**Comment by TuscanRaider** [comment] 2016-03-27 02:39
In general, is it possible to log where in the code the thread is
spinning?  It would be great to be able to debug the hangs and understand
why they are happening.

On Saturday, March 26, 2016, 49studebaker <notifications@github.com> wrote:

> If I scroll through the EPG, I get the spinning circle. I think a SageTV
> developer, told me that SageTV is retrieving data from the internet. Could
> you fork this retrieval process so that it does not slow down the interface?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/google/sagetv/issues/116>
>


-- 
-Mike

**Comment by Narflex** [comment] 2016-03-28 17:29
This data retrieval is already forked...however, it is possible to do
things in the STV that end up making the data fetching serial; which is
sometimes desired...and that's more than likely what is occurring in this
case, although it could be some other core bug in SageTV; but we need to
figure out where it's actually coming from. :) There's already a watchdog
that runs in SageTV called the AWTThreadWatcher which checks to make sure
input events are getting processed in a timely fashion; and if it notices
that queue is not progressing then it will log that there was a 'hang
detected'. Then there are other config settings which indicate that if it
is hung longer than a certain amount of time; it will then dump all of the
java thread stacks so you can see where everything is at.

The first step to fixing this would be to ensure you are on the default
SageTV7 STV with no plugins at all (since they may be the cause of this and
i want to exclude that possibility). Then next time it happens; post your
log file here and let me know at exactly what time it happened. There will
be 'hang detected' messages in the log file at that time; so that will help
a lot in identifying it.  Then i can see what thread is doing the image
loading and what type of image it's trying to load and that'll narrow
things down to some degree...and I may be able to figure it out from that;
otherwise you'll need to do it again with the thread dumping enabled; which
can cause your logs to get really big if this happens a lot.  If you want;
you can just set that one now as well...then I'd have more data to analyze
which is always good.  That property is:

ui/thread_hang_delay_to_dump

and the value is in milliseconds. By default it needs to be hung at least
750 millliseconds before the circle will show up; and I wouldn't recommend
setting this lower than 2000 or 3000. If you're using service mode (or a
separate client); then set this in SageClient.properties...otherwise set it
in Sage.properties.

On Sat, Mar 26, 2016 at 7:39 PM, TuscanRaider <notifications@github.com>
wrote:

> In general, is it possible to log where in the code the thread is
> spinning? It would be great to be able to debug the hangs and understand
> why they are happening.
>
> On Saturday, March 26, 2016, 49studebaker <notifications@github.com>
> wrote:
>
> > If I scroll through the EPG, I get the spinning circle. I think a SageTV
> > developer, told me that SageTV is retrieving data from the internet.
> Could
> > you fork this retrieval process so that it does not slow down the
> interface?
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/google/sagetv/issues/116>
> >
>
>
> --
> -Mike
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/google/sagetv/issues/116#issuecomment-201974349>
>



-- 
Jeffrey Kardatzke
jkardatzke@google.com
Google, Inc.

**Comment by 49studebaker** [comment] 2016-03-29 06:08
Here is the log file:

https://drive.google.com/file/d/0BxOPkiqHH2ppNUIzR1RRRjRiLUE/view?usp=sharing

**Comment by Narflex** [comment] 2016-03-30 18:32
OK, I can see it's when it's doing the GetChannelLogo call in the STV. I'll
take a look at the specific locations its being used in the Guide menu and
see if I can figure out which one isn't being done correctly.

One other thing I need you to verify first is that this property is at it's
default value. Make sure this is set this way in your properties file:

async_load_url_images=true

It should be at true...the only way it would be false is if you changed it
to be that way...and if you did; that would explain everything.

On Mon, Mar 28, 2016 at 11:08 PM, 49studebaker <notifications@github.com>
wrote:

> Here is the log file:
>
>
> https://drive.google.com/file/d/0BxOPkiqHH2ppNUIzR1RRRjRiLUE/view?usp=sharing
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/google/sagetv/issues/116#issuecomment-202727716>
>



-- 
Jeffrey Kardatzke
jkardatzke@google.com
Google, Inc.

**Comment by 49studebaker** [comment] 2016-03-30 18:53
I checked the sage properties file and async_load_url_images=true.

**Comment by Narflex** [comment] 2016-04-01 22:29
[SageTV7-STV.zip](https://github.com/google/sagetv/files/200511/SageTV7-STV.zip)

Try with this STV and see if that works. I found various places where it was calling GetChannelLogo just to check if the logo existed where instead it could be calling GetChannelLogoURL (which is a non-blocking call).  If it hangs up on you still...then get me the log just like you did before as maybe there are other things too.  You apparently have a good internet connection for testing this kind of thing. :)

**Comment by 49studebaker** [comment] 2016-04-02 03:50
I will test it.

"You apparently have a good internet connection for testing this kind of thing."
The spinning circle appears because my dial-up connection takes a while to download the channel logo. I got high speed internet a few weeks ago, and the spinning circle appears very briefly. Anyone with a dialup connection could test this or you could install a bandwith limiter software. If SageTV is downloading something in the background, it should not hang up the interface.

**Comment by Narflex** [comment] 2016-04-03 18:22
It does already do background downloads of URL based images in nearly all
cases. However, there are ways to make it not do it in the background
because sometimes you want to be able to force load an image.....so it's
just a few cases which we can track down where it's taking the wrong path
to do this and fix those.

Jeff Kardatzke

**Comment by Narflex** [comment] 2016-04-12 19:34
@49studebaker How's testing been going?

**Comment by 49studebaker** [comment] 2016-04-18 09:40
That fixed the problem. Thanks.

**Comment by Narflex** [comment] 2016-04-18 17:53
Fix merged (I forgot to reference this issue in it so I'll close this manually).

**Closed by Narflex** 2016-04-18 17:53 UTC
